spm_train --input=/home/rakshika/src/kapilash/dc/src/pyts/brls/spmtamilplain.txt --model_prefix=spmuni_tamil_8k --vocab_size=8000 --model_type=unigram
spm_train --input=/home/rakshika/src/kapilash/dc/src/pyts/brls/spmtamilplain.txt --model_prefix=spmuni_tamil_9k --vocab_size=9000 --model_type=unigram
spm_train --input=/home/rakshika/src/kapilash/dc/src/pyts/brls/spmtamilplain.txt --model_prefix=spmuni_tamil_10k --vocab_size=10000 --model_type=unigram
spm_train --input=/home/rakshika/src/kapilash/dc/src/pyts/brls/spmtamilplain.txt --model_prefix=spmuni_tamil_11k --vocab_size=11000 --model_type=unigram
spm_train --input=/home/rakshika/src/kapilash/dc/src/pyts/brls/spmtamilplain.txt --model_prefix=spmuni_tamil_12k --vocab_size=12000 --model_type=unigram
spm_train --input=/home/rakshika/src/kapilash/dc/src/pyts/brls/spmtamilplain.txt --model_prefix=spmbpe_tamil_8k --vocab_size=8000 --model_type=bpe
spm_train --input=/home/rakshika/src/kapilash/dc/src/pyts/brls/spmtamilplain.txt --model_prefix=spmbpe_tamil_9k --vocab_size=9000 --model_type=bpe
spm_train --input=/home/rakshika/src/kapilash/dc/src/pyts/brls/spmtamilplain.txt --model_prefix=spmbpe_tamil_10k --vocab_size=10000 --model_type=bpe
spm_train --input=/home/rakshika/src/kapilash/dc/src/pyts/brls/spmtamilplain.txt --model_prefix=spmbpe_tamil_11k --vocab_size=11000 --model_type=bpe
spm_train --input=/home/rakshika/src/kapilash/dc/src/pyts/brls/spmtamilplain.txt --model_prefix=spmbpe_tamil_12k --vocab_size=12000 --model_type=bpe
spm_train --input=/home/rakshika/src/kapilash/dc/src/pyts/brls/spmtamilpretok.txt --model_prefix=spmuni_tamil_pretok_8k --vocab_size=8000 --model_type=unigram
spm_train --input=/home/rakshika/src/kapilash/dc/src/pyts/brls/spmtamilpretok.txt --model_prefix=spmuni_tamil_pretok_9k --vocab_size=9000 --model_type=unigram
spm_train --input=/home/rakshika/src/kapilash/dc/src/pyts/brls/spmtamilpretok.txt --model_prefix=spmuni_tamil_pretok_10k --vocab_size=10000 --model_type=unigram
spm_train --input=/home/rakshika/src/kapilash/dc/src/pyts/brls/spmtamilpretok.txt --model_prefix=spmuni_tamil_pretok_11k --vocab_size=11000 --model_type=unigram
spm_train --input=/home/rakshika/src/kapilash/dc/src/pyts/brls/spmtamilpretok.txt --model_prefix=spmuni_tamil_pretok_12k --vocab_size=12000 --model_type=unigram
spm_train --input=/home/rakshika/src/kapilash/dc/src/pyts/brls/spmtamilpretok.txt --model_prefix=spmbpe_tamil_pretok_8k --vocab_size=8000 --model_type=bpe
spm_train --input=/home/rakshika/src/kapilash/dc/src/pyts/brls/spmtamilpretok.txt --model_prefix=spmbpe_tamil_pretok_9k --vocab_size=9000 --model_type=bpe
spm_train --input=/home/rakshika/src/kapilash/dc/src/pyts/brls/spmtamilpretok.txt --model_prefix=spmbpe_tamil_pretok_10k --vocab_size=10000 --model_type=bpe
spm_train --input=/home/rakshika/src/kapilash/dc/src/pyts/brls/spmtamilpretok.txt --model_prefix=spmbpe_tamil_pretok_11k --vocab_size=11000 --model_type=bpe
spm_train --input=/home/rakshika/src/kapilash/dc/src/pyts/brls/spmtamilpretok.txt --model_prefix=spmbpe_tamil_pretok_12k --vocab_size=12000 --model_type=bpe